server:
  port: 8081

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: scr/main/java
      exclude: static/**
  application:
    name: stoblog
  resources:
    static-locations: /upload/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: stodb
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/stodb?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.stoblog.mybatis.entity

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl